var connect = require('connect')
var http = require('http')
var fs = require('fs')
var custom = require('./CustomErrorHandler')
var favicon = require('serve-favicon')
var logger = require('morgan')
var staticServe = require('serve-static')

http.createServer(connect()
    .use(favicon('./public_html/favicon.ico'))
    .use(logger('dev'))
    .use(custom('./public_html', '404 File Not Found', '403 Directory Access Forbidden'))
    .use(staticServe('./public_html'))
).listen(8124)